Add more info about Wayland support to README.md
hluk/copyq-commands pull request #87
Opened 2023-11-28 15:41 UTC by Gufderald

Specify extra configuration needed for terminal emulators.

Related to https://github.com/hluk/copyq-commands/issues/86

2023-12-09 06:42 UTC, hluk requested changes
Thanks for the patch. Just one correction.

2023-12-09 06:42 UTC, hluk commented on Scripts/README.md
> +Paste behaviour is implemented with Shift+Enter shortcut. It works in most
```suggestion
Paste behaviour is implemented with Shift+Insert shortcut. It works in most
```

2023-12-21 11:28 UTC, Gufderald commented on Scripts/README.md
> +Paste behaviour is implemented with Shift+Enter shortcut. It works in most
Oh, that's right! Thanks!

2023-12-22 12:44 UTC, merged

2023-12-22 12:44 UTC, hluk commented
Thanks